### ISSUE TITLE
[API-UPDATE] Need to update to accommodate recent API changes in AUTOMATIC1111

### ISSUE THREAD

**Issue by PhoenixCreation** [Mikubill/sd-webui-controlnet#567]
# What Happened
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8187 got merged recently.
- This allows user to use Controlnet and other scripts from the `/sdapi/v1/txt2img` and `sdapi/v1/img2img` with parameter ` alwayson_scripts`.
- This will allow us to now deprecate the `/controlnet/txt2img` and `/controlnet/img2img` routes as mentioned in wiki.

# Issue 1
- I haven't understood entire flow of the AUTOMATIC1111's API but I will try my best to explain this.
- Currently `ScriptRunner` class has `process` method which is responsible to pass on arguments to the other scripts like Controlnet.
- ScriptRunner.process will call Script.process method with expected method signature of `process(self, p, *args):` which will allow all scripts to be run with API.
- For Controlnet script's Script.process method has different signature ` process(self, p, is_img2img=False, is_ui=False, *args)` which is causing trouble if we want to just directly use the Controlnet from the  `/sdapi/v1/txt2img` API because first two parameters will go towards the `is_img2img` and `is_ui`.
- So current schema for the Controlnet parameters will become as following for solution of this issue:
```python
"ControlNet": [
  false,  # is_img2img
  false,  # is_ui
  true,   # enabled,
  "canny",    # module,
  "control_canny-fp16 [e3fe7712]",    # model,
  1,    # weight,
  {"image":"BASE64_IMAGE_STRING"},    # image,
  false,    # scribble_mode,
  "Scale to Fit (Inner Fit)",   # resize_mode,
  false,    # rgbbgr_mode,
  false,    # lowvram,
  512,    # pres,
  100,    # pthr_a,
  200,    # pthr_b,
  0,    # guidance_start,
  1,    # guidance_end,
  false   # guess_mode
]
```
Ref: https://github.com/Mikubill/sd-webui-controlnet/blob/5bf7e54e8ef82f013d4b304184b60cdb52810362/scripts/controlnet.py#L610
This is current workaround and I am mentioning this because Second issue is dependent on this.

Curl Command for the Request :https://pastebin.com/432EG3PT

# Issue 2
- If you go ahead and send the curl request mentioned above then you will encounter KeyError for 'image' for following line of code: https://github.com/Mikubill/sd-webui-controlnet/blob/5bf7e54e8ef82f013d4b304184b60cdb52810362/scripts/controlnet.py#L751
- Basically image['image'] is currently string not numpy array of image.
- This is also mentioned in the description of the https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8187
- >For exemple, controlnet might have to detect that the images are a base64 string instead of an Image but it shouldn't require much work.
- I will be raising PR for this detection check. But till then it won't work. Edit: Raised PR(#568)

I am creating this issue so we can keep track of the API related changes. Also let me know if Issue 1 needs to be changing but that is something you should handle as you have more knowledge of the API flow.

# Tasks
- [x] Raise PR for image str detection(#568)
- [ ] Mark APIs `/controlnet/txt2img` and `/controlnet/img2img`  as deprecated.
- [ ] Update wiki accordingly. [I guess this needs to be done by owner]

**Comment by Vespinian** [comment]
For posterity, at time of writing and to my understanding, the way args for scripts work in auto1111 is that there is a giant list of args that cover all scripts. Each script gets handed a args_from and args_to variable to know where their args are in that list. One of the things I did in my PR is to initialize that list with None everywhere and then fill it in with whatever is passed in the API request instead of not generating one at all or a very limited one when using selectable scripts. After initializing the arg list with None in every position to the correct size to cover all scripts, the API request finds the script you specified in the `alwayson_scripts` dict, checks if it has args in the request and places those args at their intended position in the big arg list.

If I recall correctly, in the case of controlnet, the number of args will depend on the max controlnet modules you have. While only filling one module, if you have more then one, might not be a problem, you can essentially fill everything. So the controlnet API might benefit from a get config or get max_model api route, if it hasn't already got one, which would allow the client to know how many controlnet modules he can pass and the schema in the docs might want to account for this.

**Comment by PhoenixCreation** [comment]
> If I recall correctly, in the case of controlnet, the number of args will depend on the max controlnet modules you have. While only filling one module, if you have more then one, might not be a problem, you can essentially fill everything. So the controlnet API might benefit from a get config or get max_model api route, if it hasn't already got one, which would allow the client to know how many controlnet modules he can pass and the schema in the docs might want to account for this.

@Vespinian, I understood that concept but the issue is that two args(is_img2img and is_ui) are already there in process method of controlnet script which throws of the count of arguments to be passed on. 

Currently each controlnet model takes 15 args(ref:https://github.com/Mikubill/sd-webui-controlnet/blob/5bf7e54e8ef82f013d4b304184b60cdb52810362/scripts/controlnet.py#L72) and so basically one should only need to provide 15 arguments to run single controlnet and 30 arguments to run two controlnet and so on. But due to the predefined args(is_img2img and is_ui) you need to pass two extra args in first and second element of arrays for them manually. so total args count for 1 controlnet will become 17, for two it would be 32 and so on. Which I think is okay, but can be refactored to be removed. 

But this is great thing as it will allow all AUTOMATIC1111 scripts to be streamlined into single flow format.

**Comment by killamonis** [comment]
The curl command linked above is unable to be viewed ("Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it."). 

I've tried to use the alwayson_scripts with the sdapi/v1/txt2img route and I'm still not getting images using responses, not sure if I'm formatting things incorrectly.

**Comment by Vespinian** [comment]
Exemple `alwayson_scripts`, the 2 inline args are `is_img2img` and `is_ui`, the rest are the 15 args for the controlnet, if you want to use multiple nets you just append another 15 args in the list for each module.
```json
    "alwayson_scripts": {
      "ControlNet": {
        "args": [false, false,
            true,
            "none",
            "difference_controlSd15Openpose [1723948e]",
            1.0,
            {"image": "base64img..."},
            false,
            "Scale to Fit (Inner Fit)",
             false,
             false,
             64,
             64,
             64,
            0.0,
            1.0,
            false
            ]
        }
    }
```

**Comment by killamonis** [comment]
@Vespinian 
tried running the API call with that format and got this error

```
422
api call made
{'detail': "Script 'ControlNet' not found"}
```


My call body 
```
"prompt": prompt,
            "negative_prompt": "",
            "seed": -1,
            "subseed": -1,
            "subseed_strength": 0,
            "batch_size": 1,
            "n_iter": 1,
            "steps": 20,
            "cfg_scale": 7,
            "width": 512,
            "height": 512,
            "restore_faces": True,
            "eta": 0,
            "sampler_index": "Euler a",
            "alwayson_scripts": {
                "ControlNet": [
                    False,  # is_img2img
                    False,  # is_ui
                    True,   # enabled,
                    "canny",    # module,
                    "control_sd15_canny [fef5e48e]",    # model,
                    0.3,    # weight,
                    {"image":[b64img]},    # image,
                    False,    # scribble_mode,
                    "Scale to Fit (Inner Fit)",   # resize_mode,
                    False,    # rgbbgr_mode,
                    False,    # lowvram,
                    512,    # pres,
                    100,    # pthr_a,
                    200,    # pthr_b,
                    0,    # guidance_start,
                    1,    # guidance_end,
                    False   # guess_mode
                ]
            }
```

**Comment by killamonis** [comment]
When I use controlnet through the UI it works

**Comment by ljleb** [comment]
related: #527 and #528

Didn't think auto would merge the alwayson scripts PR so quickly. in #527 I tried changing how the args of gradio are passed so that we can accept dicts instead of an unreasonably long list of arguments to keep the api as close to what it is right now. I'll try spending a bit of time on this to see if it can be a good fix to the situation.

**Comment by PhoenixCreation** [comment]
Hi @killamonis, Can you confirm following things?
- Have you updated the controlnet extension and AUTOMATICA1111 to latest version? If yes, Can you please provide last commit id for both of them?
- If you have updated both of them, run the curl command from https://pastebin.com/432EG3PT, and let us know if it still gives the same error.

**Comment by ljleb** [comment]
> @Vespinian If I recall correctly, in the case of controlnet, the number of args will depend on the max controlnet modules you have.

That is only true for the gradio interface. In the web API, you can pass an arbitrary number of control net units and the webui will resize the script args of the controlnet script to match the passed args.

**Comment by Vespinian** [comment]
Alright. Also I believe that in the alwayson scripts PR, the way the arg list is initialized is currently overwriting the modifications made by the scriptrunner hijack, which broke the API hijack, see #571. I made a bit of a dirty fix in a branch of my fork by taking the control units from the request and creating a ControlNet dict in the request's alwayson_scripts but that may have broken other things.

**Comment by ljleb** [comment]
Yes, thanks for your quick fix. I opened #527 for this purpose, hopefully I can get some confidence on the code and will open for review when we get there.

**Comment by ImranBug** [comment]
I am getting this error:
`
Error running process: C:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "...\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 682, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 477, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 488, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None
`

My code:
`
    "alwayson_scripts": {},
    "controlnet_units": [
        {
            "input_image": image_string,
            "module": "openpose",
            "model": "control_sd15_openpose [fef5e48e]",
        }
    ]
    `

Any idea if this is related to this ongoing update or may be I should create a new bug?

**Comment by killamonis** [comment]
> Hi @killamonis, Can you confirm following things?
> 
> * Have you updated the controlnet extension and AUTOMATICA1111 to latest version? If yes, Can you please provide last commit id for both of them?
> * If you have updated both of them, run the curl command from https://pastebin.com/432EG3PT, and let us know if it still gives the same error.

Hey @PhoenixCreation 
Updating the controlnet extension allowed me to actually send the controlnet request, but when I send it through the API, I'm getting this error, and the generated image doesn't use the controlnet pose. 

<img width="1158" alt="Screenshot 2023-03-13 at 5 27 57 PM" src="https://user-images.githubusercontent.com/52933919/224861362-d3a750de-b5aa-4bc3-9dae-009a28c0f65b.png">

Automatic commit: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/dfeee786f903e392dbef1519c7c246b9856ebab3

Controlnet extension commit: 274dd5df217a03e059e9cf052447aece81bbd1cf

**Comment by freecoderai01** [comment]
I'm unable to run the extension in img2img mode. Not sure if related to current issue.
(tested on latest commit of automatic, https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2)
The output with error
```
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 409, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 737, in process
    resize_mode = resize_mode_from_value(resize_mode)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 184, in resize_mode_from_value
    return ResizeMode(value)
  File "/usr/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'OUT' is not a valid ResizeMode
```

**Comment by ljleb** [comment]
Hi @freecoderai01, can you elaborate how you interact with the extension? The value `'OUT'` is not a valid resize mode, I assume this was passed directly as `"resize_mode": "OUT"` in the API? If that is the case, consider using int value `2` or the string `"Envelope (Outer Fit)"` as documented in the wiki.

Otherwise, please clarify what situation caused the error.

**Comment by freecoderai01** [comment]
> Hi @freecoderai01, can you elaborate how you interact with the extension? The value `'OUT'` is not a valid resize mode, I assume this was passed directly as `"resize_mode": "OUT"` in the API? If that is the case, consider using int value `2` or the string `"Envelope (Outer Fit)"` as documented in the wiki.
> 
> Otherwise, please clarify what situation caused the error.

Hi @ljleb, I was not trying to use the extension's API, so the value should be in the default state, isn't it? 
For context, I was interacting via automatic1111 webui (running inside google colab, without --api arg, full list of args: 
--disable-safe-unpickle --enable-insecure-extension-access --share --gradio-img2img-tool editor --theme dark --ckpt-dir /content/stable-diffusion-webui/models/Stable-diffusion --gradio-queue --disable-console-progressbars --no-hashing --opt-channelslast --xformers), 
img2img tab with controlnet subtab. Gradio: 3.16.2.  While using web browser, switching between  Just Resize/Scale to Fit (Inner Fit)/Envelope (Outer Fit) did not affect the problem.

**Comment by ljleb** [comment]
Thanks for the context. I think this should go in its own issue, it does not seem related to the API migration.

**Comment by mengchengwanli** [comment]
> 

这样做可能会遇到的一个潜在问题是，如果用户将 controlnet 脚本替换为脚本运行器中的副本。我不认为这是一个阻塞问题，因为它可能不会发生，但它可能会导致令人惊讶的行为。

在未更改的 SD 安装上进行常规 api 调用时，会发生这种情况吗？我不完全了解这个问题以及它将如何影响脚本的行为，但是一旦我完成了重新映射对象和迁移调用，我可以帮助测试内容。

￼
合作者
作者
ljleb 评论 2 days ago • 
编辑 


This parameter error, do not understand why;
Using the original parameter passing mode can be achieved;
